### ISSUE TITLE
Stripping a File Gives Permissions Error Replacing Same File

### ISSUE THREAD

**Issue by tmcconechy** [nuzzio/grunt-strip-code#11]
I am using the following example..

  strip_code: { // jshint ignore:line
     options: {
      start_comment: 'start-remove',  // jshint ignore:line
      end_comment: 'end-remove',  // jshint ignore:line
    },
    src: 'dist/js/sohoxi.js'
  },

In my grunt file i combine a bunch of files into a dist folder...
  grunt.registerTask('default', ['revision', 'jshint', 'sass', 'concat', 'strip_code',

So the strip_code task runs after concat. No matter what i try i get the error Warning: Unable to write "src" file (Error code: EISDIR). Use --force to continue.

So it seems it is unable to strip and replace in the same file?

**Comment by nuzzio** [comment]
Hello @tmcconechy check out the new version when you get a chance and see if it addresses the issue you are describing.
