### ISSUE TITLE
Support for HTML comments?

### ISSUE THREAD

**Issue by dsquier** [nuzzio/grunt-strip-code#13]
The only other Grunt module I've found to do this is https://github.com/adamatnetrist/grunt-redacter, which doesn't appear to have much usage.

EDIT: Just noticed there is recent activity in the Develop branch. Going to give that a shot.

**Comment by dsquier** [comment]
Looking over the code, this does not appear possible without providing a custom RegEx. I'd like to module to look at the file extension and choose an appropriate RegEx filter. I may end up forking this repo and building out this functionality. In the meantime, the following RegEx can be used for HTML parsing:

```
    // Used for HTML comments, i.e., "<!-- COMMENT -->"
    var HtmlFilter = new RegExp(
          "[\\s ]*<!\\-\\- " + options.start_comment + " \\-\\->"
          + "?[\\s\\S]*?"
          + "[\\s ]*<!\\-\\- " + options.end_comment + " \\-\\->[\\s ]*\\n?"
        , "g");
```

**Comment by dsquier** [comment]
FWIW, I added this functionality and put it up into an NPM module:

https://www.npmjs.com/package/grunt-stripper

Basically, it will use a different RegEx if it encounters an HTML (.html) file. This adds support for removing code between HTML comment blocks; a big need I had in my project.

Otherwise, looks like the next version of this library (in Dev branch) will have a much more robust implementation thanks to work from @nuzzio and @ZuBB here:

https://github.com/nuzzio/grunt-strip-code/pull/6

**Comment by dsquier** [comment]
Due to a need for an npm solution that handled HTML comment blocks, I took this library and added support for HTML blocks via a custom regex based on file extension.

https://www.npmjs.com/package/grunt-stripper

There appears to be good work going on in the Develop branch, which will make this a lesser solution. Until then, it solves my problem :)

**Comment by nuzzio** [comment]
Hello @dsquier, check out the new version when you get a chance and see if it addresses your requirement.

**Comment by dsquier** [comment]
Will do, thanks!
