### ISSUE TITLE
How to strip code only from production files?

### ISSUE THREAD

**Issue by dKab** [nuzzio/grunt-strip-code#14]
I need test code to be stripped only from production files but remain in my source files. I could do concatenation to generate one file and then use the plugin to strip test code from it. But I use requirejs and I can't think of any way to achieve that. I need my sources  to be already stripped from test code, because if run r.js first - it will delete all comments and I won't be able to use grunt-stip-code.
If I run grunt-strip-code first - I end up with my sources being stripped from test code and that's not what I want. Any ideas on how to achieve desired effect in this situation?

**Comment by andrewGarson** [comment]
r.js allows you to preserve certain comments for preserving licenses. I think you need to format
/*! some comment here */

https://github.com/jrburke/r.js/issues/41

**Comment by nuzzio** [comment]
Maybe if you had grunt tasks for:
- `dev-build` which would have only the grunt requirejs task `src to dist/dev`
- `prod-build` which would have the strip-code task `src` to `tmp` followed by the grunt requires task `tmp to dist/prod`

Would that help?

**Comment by dKab** [comment]
Thanks, that could help, but I don't have time to check it these days, so closing this one.
