### ISSUE TITLE
image files should not be processed

### ISSUE THREAD

**Issue by muhawo** [nuzzio/grunt-strip-code#16]
I think it should exclude binary files automatically. For several times, I destroied image files.

**Comment by nuzzio** [comment]
I will take a look at this. Thank you.

**Comment by nuzzio** [comment]
@muhawo can you post you task configuration here? I am curious as to why you can't exclude the binary files in the target.

**Comment by muhawo** [comment]
yes , you are right. I should exclude the image files.
I just forgot to configure that, and then the problem came.
Other plugins, such as template or replace, may also cause such problem.
