### ISSUE TITLE
won't strip code

### ISSUE THREAD

**Issue by petereberlecom** [nuzzio/grunt-strip-code#18]
Hi,
love this tool! (on my pc)
But on my coworker's pc it just won't strip. 

all i see is: `No code was stripped from file: ...`

we tried a lot of things like using the cmd as admin. installing over and over again. But i have no idea why it won't strip? 

He uses a pc with win 10.

**Comment by gregwhitworth** [comment]
@petereberlecom Were you able to figure this out? I'm hitting the same thing.

**Comment by petereberlecom** [comment]
@gregwhitworth Kind of, we figured out that the regex was kind of faulty. So instead of a string we used a custom regex then it worked.

**Comment by gregwhitworth** [comment]
Thanks @petereberlecom that worked for me as well. Do you mind re-opening this issue, I think it's worth tracking for @nuzzio and possibly adding it to the documentation for the time being if it can't be fully addressed.

**Comment by petereberlecom** [comment]
@gregwhitworth sure, glad it helped you :)

**Comment by nuzzio** [comment]
Oh hmm it would be helpful to have the string that tripped the regex generator. Would you be able to post that when you get a chance?

**Comment by gregwhitworth** [comment]
I used `/* strip code block start */` and `/* strip code block end*/`, similar to your example - I actually even tried your example one. Thank you for the tool and support, it's greatly appreciated.

**Comment by nuzzio** [comment]
Sure, and thank you for taking the time to let me know about this. Would you specify a few items for me? I would like to recreate the issue and test for it:

OS & version
Node version
Grunt version

**Comment by nuzzio** [comment]
I pushed out a new version with windows testing, all tests pass on AppVeyor (Windows). If you can help me reproduce the error you were experiencing, it would be useful.

**Comment by nuzzio** [comment]
Closing this for now, until a reproducible error can be produced.
