### ISSUE TITLE
Block Stripping Changes

### ISSUE THREAD

**Issue by nuzzio** [nuzzio/grunt-strip-code#2]
I found myself needing to make a more flexible version of your plugin that would accommodate dynamic comment blocks, and multiple types of those blocks.

I can submit a pull request if you are interested in them. 

This is the repo: https://github.com/nuzzio/grunt-strip-code

Let me know,
Thanks

**Comment by nuzzio** [comment]
Hi @philipwalton,

I am in the process of releasing a new version for it and was wondering if you would add me as a package owner on the npm registry.

https://docs.npmjs.com/cli/owner

This way I will be able to change the information on it and not disrupt the users that use the task.

I would be grateful if you would let me know if you can do this.

Thank you very much.

**Comment by philipwalton** [comment]
No problem, I added you. Let me know if it's not working.

**Comment by nuzzio** [comment]
Looks good, thank you Phillip.
