### ISSUE TITLE
grunt-strip-code places file under /src

### ISSUE THREAD

**Issue by mhmpl** [nuzzio/grunt-strip-code#7]
Hi!
I'm trying out your Grunt plugin and have the following problem.
First of all, this is my `strip_code` configuration:
```javascript
strip_code : {
  options : {
    pattern : /(\<\!--) @formatter:(off|on) -->/g
  },
  src : 'dist/index.html'
}
```

With this, I'm trying to remove IntelliJ's `<!-- @formatter:on -->` commands.
If I get your documentation right, the `strip_code` task should place the edited file on the same place which was defined in the `src` attribute, however, `strip_code` will save the new file as `<root>/src`.

I don't get what I'm doing wrong here.

**Comment by jelly972** [comment]
Hi, 

if anyone still uses it, documentation is incorrect 
the src is actually an object, so the above configuration would be:

strip_code : {
  options : {
    pattern : /(\<\!--) @formatter:(off|on) -->/g
  },
  src : {src: 'dist/index.html', dest: 'dist/index.html'}
}

good luck

**Comment by nuzzio** [comment]
The docs have been updated. Let me know if you still have issues.
