### ISSUE TITLE
Problem with files array

### ISSUE THREAD

**Issue by rhernandog** [nuzzio/grunt-strip-code#9]
Hi,

I'm getting an error when passing an array of files in the config object. This is how it looks
```javascript
grunt.initConfig({

    strip_code : {
      options : {
        start_comment : 'start_remove_here',
        end_comment : 'end_remove_here'
      },
      files : [{src:"scripts/a.js", dest : "scripts/a-strip.js"},{src:"scripts/b.js", dest : "scripts/b-strip.js"}]
    },// strip_code end

  });// init config end
```

And this is the error I'm getting:
```
Warning: Object #<Object> has no method 'indexOf'
```

Any help will be appreciated.

Thanks,
Rodrigo.

**Comment by rhernandog** [comment]
Hi,

In case anyone needs it, I created an extremely simple task to remove everything between two specific delimiters. Also those delimiters can be present as many times as you want in the code.

Here's the task code to include in the Gruntfile.js:
```javascript
grunt.registerMultiTask('removeBlock', function() {

    // set up a removal regular expression
    var removalRegEx = new RegExp('(\/\/ ' + this.options()[0] + ' \/\/)(?:[^])*?(\/\/ ' + this.options()[1] +  ' \/\/)', 'g');

    this.data.forEach(function(fileObj){

      var sourceFile = grunt.file.read( fileObj.src ),
          removedFile = sourceFile.replace( removalRegEx, '' ),
          targetFile = grunt.file.write( fileObj.dest, removedFile );

    });// for each loop end

  });
```

Then usage is like this:
```javascript
grunt.initConfig({

    removeBlock: {
      options : ["REMOVE START", 'REMOVE END'],
      files : [{src:'scripts/a.js', dest:'scripts/a-clean.js'}, {src : 'scripts/b.js', dest : 'scripts/b-clean.js'}]
    }

});// init config end
```

Finally the only catch for this particular task is that in your code the start and end removal strings should start with a double forward slash and then a space, and should end with a space and two forward slash. In this case I'm using "REMOVE START" and "REMOVE END", so the code should be like this
```javascript
function notEliminated() {
  console.log( 'foo' );
}

// REMOVE START //
function willBeEliminated() {
  conosle.log( 'bar' );
}
// REMOVE END //

// this code won't be eliminated
function foo() {
  return "bar";
}

// REMOVE START //
function baz() {
  return 'this will be eliminated too!!';
}
// REMOVE END //
```

Of course this is very primitive but it suits my needs at the moment, hopefully this will come in handy and perhaps someone could polish it in order to make it more robust.

Cheers,
Rodrigo.

**Comment by davidjbradshaw** [comment]
@rhernandog Thank you this was useful, you should publish it on npm.

**Comment by nuzzio** [comment]
@rhernandog The original issue was caused by an error in the docs.

Your code should declare the src property as follows:

```javascript
grunt.initConfig({

    strip_code : {
      options : {
        start_comment : 'start_remove_here',
        end_comment : 'end_remove_here'
      },
     your_target: {
       files : [{src:"scripts/a.js", dest : "scripts/a-strip.js"},{src:"scripts/b.js", dest : "scripts/b-strip.js"}]
     }
    },// strip_code end

  });// init config end
```
